export const LOAD_CLIENTS_REQUEST = 'client/LOAD_REQUEST'
export const LOAD_CLIENTS_SUCCESS = 'client/LOAD_SUCCESS'
export const LOAD_ALL_CLIENTS_SUCCESS = 'client/LOAD_ALL_SUCCESS'
export const LOAD_CLIENTS_FAILURE = 'client/LOAD_FAILURE'

export const SAVE_CLIENT_SUCCESS = 'client/SAVE_CLIENT_SUCCESS'
export const SAVE_CLIENT_FAILURE = 'client/SAVE_CLIENT_FAILURE'
export const SELECTED_CLIENT = 'client/SELECTED_CLIENT'
export const REMOVE_SELECTED_CLIENT = 'client/REMOVE_SELECTED_CLIENT'

export const LOAD_STATISTICS_REQUEST = 'client/LOAD_STATISTICS_REQUEST'
export const LOAD_STATISTICS_SUCCESS = 'client/LOAD_STATISTICS_SUCCESS'
export const LOAD_STATISTICS_FAILURE = 'client/LOAD_STATISTICS_FAILURE'

export const LOAD_CHANGE_STATUS_SUCCESS = 'client/LOAD_CHANGE_STATUS_SUCCESS'
export const LOAD_CHANGE_STATUS_FAILURE = 'client/LOAD_CHANGE_STATUS_FAILURE'